#!/bin/bash

echo "

####################################################################################################################################
You're in a Docker environment!  Type exit to leave (or control-D).  You can also find all the examples at your home directory /root
####################################################################################################################################

helpful commands:

    ls          list files
    cd          change directory
    nodejs      use NodeJS to evaluate scripts

"

exec /bin/bash